version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/datasweet/jsonmap
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run:
          name: run tests
          command: |
            dep ensure
            go fmt ./...
            go vet ./...
            go test -v ./...
